include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    lines_longer_than_80_chars: true
    require_trailing_commas: true
    always_use_package_imports: true
    prefer_single_quotes: true

    errors:
      invalid_annotation_target: ignore

analyzer:
  exclude:
    - '**/*.g.dart'
